title: MDN Search
email: mdn@chaitanyapramod.com
description: >- 
  Search MDN web documentation right from your Chrome omnibox/addressbar
url: https://mdnsearch.chaitanyapramod.com
logo: /assets/images/mdn-search.svg
twitter_username: ChaitanyaPramod
github_username: ChaitanyaPramod 

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-seo-tag

google_analytics: UA-114772362-1

twitter:
  username: ChaitanyaPramod
facebook:
  username: ChaitanyaPramod

author:
  name: Chaitanya Pramod
  twitter: ChaitanyaPramod
  github: ChaitanyaPramod
  facebook: ChaitanyaPramod

minimal_mistakes_skin: "contrast"
